#!/bin/sh -e

# Create fake user and group with the same ids than
# the host user, and use its identity all along
# in the container so that all created files in
# mounted volumes with belong to the host user.
#
# https://stackoverflow.com/questions/41857462

# Create fake user
grep -q ^dummy: /etc/group || groupadd -g $GROUP_ID dummy
grep -q ^dummy: /etc/passwd || useradd -u $USER_ID -g $GROUP_ID dummy

mkdir -p /home/dummy/.ssh
# Setup SSH configuration
cat <<EOF > /home/dummy/.ssh/config
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
EOF
chown -R dummy:dummy /home/dummy

# Grants write permissions to some paths
for path in /.jupyter /.local /opt/src ; do
	mkdir -p "$path"
	chmod 777 "$path"
	chmod +t "$path"
done

case "$1" in
	sh|bash)
		exec $@
		;;
	*)
		gosu dummy "$@"
		;;
esac
